use crate::error::{LauncherError, LauncherResult};
use crate::loader_manifests;
use sha1::{Digest as Sha1Digest, Sha1};
use sha2::{Digest, Sha256};

/// Raw SHA-256 hex digest of a byte slice.
pub fn sha256_hex(data: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(data);
    hex::encode(hasher.finalize())
}

/// Lowercase SHA-1 hex digest of a byte slice.
pub fn sha1_hex(data: &[u8]) -> String {
    let mut hasher = Sha1::new();
    hasher.update(data);
    hex::encode(hasher.finalize())
}

/// Deterministic SHA-256 of a JSON payload after stripping volatile keys.
///
/// Fabric rewrites `time`/`releaseTime` on every request, so the raw response hash
/// is unstable. This mirrors `_stable_json_sha256` in `scripts/fetch_loader_manifests.py`.
pub fn stable_json_sha256(data: &[u8]) -> Option<String> {
    let value: serde_json::Value = serde_json::from_slice(data).ok()?;
    let mut obj = value;
    if let serde_json::Value::Object(map) = &mut obj {
        map.remove("time");
        map.remove("releaseTime");
    }
    let canonical = serde_json::to_string(&obj).ok()?;
    let mut hasher = Sha256::new();
    hasher.update(canonical.as_bytes());
    Some(hex::encode(hasher.finalize()))
}

/// Compute the expected hash for a loader file. Profile JSONs (Fabric/Quilt)
/// use the stable normalized hash; installer jars use the raw hash.
pub fn compute_loader_hash(loader: &str, _file_name: &str, file_type: &str, data: &[u8]) -> String {
    if file_type == "profile_json" && (loader == "fabric" || loader == "quilt") {
        if let Some(stable) = stable_json_sha256(data) {
            return stable;
        }
    }
    sha256_hex(data)
}

/// Download bytes from a URL using a redirect-safe client.
///
/// Redirects are only followed when the target host is on the embedded loader
/// domain allowlist, preventing SSRF via compromised/malicious pinned hosts.
pub async fn download_bytes(url: &str) -> LauncherResult<Vec<u8>> {
    let client = reqwest::Client::builder()
        .redirect(reqwest::redirect::Policy::custom(|attempt| {
            if let Some(host) = attempt.url().host_str() {
                if loader_manifests::is_allowed_host(host) {
                    return attempt.follow();
                }
            }
            attempt.stop()
        }))
        .user_agent("AgoraLoaderManifestBot/1.0")
        .build()
        .map_err(|e| LauncherError::Generic {
            code: "ERR_NETWORK".to_string(),
            message: format!("Failed to build HTTP client: {e}"),
        })?;

    let resp = client
        .get(url)
        .send()
        .await
        .map_err(|_| LauncherError::NetworkOffline)?;

    if !resp.status().is_success() {
        return Err(LauncherError::Generic {
            code: "ERR_NETWORK".to_string(),
            message: format!("HTTP {} for {}", resp.status(), url),
        });
    }

    resp.bytes()
        .await
        .map(|b| b.to_vec())
        .map_err(|_| LauncherError::NetworkOffline)
}

/// Download a loader file and verify its hash against the pinned value.
pub async fn download_verified(
    loader: &str,
    file_name: &str,
    file_type: &str,
    url: &str,
    expected_sha: &str,
) -> LauncherResult<Vec<u8>> {
    loader_manifests::ensure_allowed_domain(url)?;
    let data = download_bytes(url).await?;
    let actual = compute_loader_hash(loader, file_name, file_type, &data);

    if actual != loader_manifests::strip_sha_prefix(expected_sha) {
        return Err(LauncherError::HashMismatch);
    }
    Ok(data)
}

#[cfg(test)]
mod tests {
    use super::stable_json_sha256;

    /// Parity fixture for the Python `_stable_json_sha256` implementation in
    /// scripts/fetch_loader_manifests.py. The expected hash is generated by the
    /// canonical form: drop `time`/`releaseTime`, sort keys, compact separators,
    /// ensure_ascii=False. If this test fails, loader profile pins will also fail.
    #[test]
    fn stable_json_sha256_matches_python_canonicalization() {
        let data = br#"{"releaseTime":"2026","time":"2026","id":"x","libraries":[1,2]}"#;
        let actual = stable_json_sha256(data).expect("valid json");
        assert_eq!(
            actual,
            "25b887d98e1f7bd37f1daa9e77376854827c62548f6bbf0b4b28e7e4477a75f9"
        );
    }

    #[test]
    fn stable_json_sha256_is_order_independent() {
        let a = br#"{"time":"t","releaseTime":"r","id":"a"}"#;
        let b = br#"{"releaseTime":"r","id":"a","time":"t"}"#;
        assert_eq!(stable_json_sha256(a), stable_json_sha256(b));
    }
}
