use crate::error::{LauncherError, LauncherResult};
use serde::Deserialize;
use std::sync::OnceLock;

/// Embedded copy of `loader-manifests/loader_manifests.json`.
///
/// Generated by `scripts/fetch_loader_manifests.py` / `scripts/refresh_loader_manifests.py`.
/// Pinning happens at compile time; the launcher never trusts an unpinned loader version.
const LOADER_MANIFESTS: &str = include_str!("../../../loader-manifests/loader_manifests.json");

/// Embedded copy of `loader-manifests/minecraft_versions.json`.
///
/// Generated by `scripts/refresh_loader_manifests.py` from Mojang's official
/// version manifest. Contains every stable Minecraft release (1.0 → current).
const MC_VERSIONS: &str = include_str!("../../../loader-manifests/minecraft_versions.json");

#[derive(Debug, Deserialize, Clone)]
pub struct LoaderEntry {
    pub mc_version: String,
    pub loader_version: String,
    pub source_url: String,
    pub sha256: String,
    pub file_name: String,
    pub file_type: String,
}

#[derive(Debug, Deserialize)]
struct LoaderManifests {
    #[serde(default)]
    domain_allowlist: Vec<String>,
    #[serde(default)]
    loaders: std::collections::BTreeMap<String, Vec<LoaderEntry>>,
}

static MANIFEST: OnceLock<LoaderManifests> = OnceLock::new();
static MC_VERSIONS_LIST: OnceLock<Vec<String>> = OnceLock::new();

/// Parse the embedded loader manifests once and cache the result.
fn manifest() -> &'static LoaderManifests {
    MANIFEST.get_or_init(|| {
        serde_json::from_str(LOADER_MANIFESTS).unwrap_or_else(|_| LoaderManifests {
            domain_allowlist: Vec::new(),
            loaders: std::collections::BTreeMap::new(),
        })
    })
}

/// Parse the embedded Mojang version list once and cache the result.
fn mc_versions_list() -> &'static [String] {
    MC_VERSIONS_LIST.get_or_init(|| {
        serde_json::from_str(MC_VERSIONS).unwrap_or_default()
    })
}

/// Find a pinned loader entry for a `(loader, mc_version, loader_version)` tuple.
pub fn find_entry(
    loader: &str,
    mc_version: &str,
    loader_version: &str,
) -> Option<&'static LoaderEntry> {
    manifest()
        .loaders
        .get(loader)
        .and_then(|entries| {
            entries.iter().find(|e| {
                e.mc_version == mc_version && e.loader_version == loader_version
            })
        })
}

/// Verify that a URL's host is on the hard-coded modloader domain allowlist.
pub fn ensure_allowed_domain(raw_url: &str) -> LauncherResult<()> {
    let host = reqwest::Url::parse(raw_url)
        .map_err(|e| LauncherError::Generic {
            code: "ERR_UNTRUSTED_SOURCE".to_string(),
            message: format!("Invalid loader URL: {e}"),
        })?
        .host_str()
        .ok_or(LauncherError::UntrustedSource)?
        .to_string();

    if is_allowed_host(&host) {
        Ok(())
    } else {
        Err(LauncherError::UntrustedSource)
    }
}

/// Whether a host is on the embedded loader domain allowlist.
pub fn is_allowed_host(host: &str) -> bool {
    manifest().domain_allowlist.iter().any(|d| d == host)
}

/// List pinned loader entries for a loader + Minecraft version.
pub fn list_versions(loader: &str, mc_version: &str) -> Vec<&'static LoaderEntry> {
    manifest()
        .loaders
        .get(loader)
        .map(|entries| {
            entries
                .iter()
                .filter(|e| e.mc_version == mc_version)
                .collect()
        })
        .unwrap_or_default()
}

/// Distinct loader names present in the embedded manifests (sorted A→Z).
pub fn list_loaders() -> Vec<&'static str> {
    manifest().loaders.keys().map(|k| k.as_str()).collect()
}

/// All stable Minecraft versions (from Mojang's manifest), or only those
/// supported by a specific loader. Sorted newest-first.
pub fn list_mc_versions(loader: Option<&str>) -> Vec<String> {
    let all_versions = mc_versions_list();
    match loader {
        None => all_versions.to_vec(),
        Some(l) => {
            let supported: std::collections::HashSet<&str> = manifest()
                .loaders
                .get(l)
                .map(|entries| entries.iter().map(|e| e.mc_version.as_str()).collect())
                .unwrap_or_default();
            all_versions
                .iter()
                .filter(|v| supported.contains(v.as_str()))
                .cloned()
                .collect()
        }
    }
}

/// Convert a `sha256:hex` string to raw lowercase hex.
pub fn strip_sha_prefix(s: &str) -> &str {
    s.strip_prefix("sha256:").unwrap_or(s)
}

/// --- Tests ---

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_allowed_loader_domain() {
        assert!(is_allowed_host("files.minecraftforge.net"));
        assert!(is_allowed_host("maven.fabricmc.net"));
        assert!(is_allowed_host("maven.neoforged.net"));
        assert!(is_allowed_host("maven.quiltmc.org"));
        assert!(is_allowed_host("neoforged.net"));
    }

    #[test]
    fn test_disallowed_localhost() {
        assert!(!is_allowed_host("127.0.0.1"));
    }

    #[test]
    fn test_disallowed_metadata_ip() {
        assert!(!is_allowed_host("169.254.169.254"));
    }

    #[test]
    fn test_disallowed_random_host() {
        assert!(!is_allowed_host("evil.com"));
    }

    #[test]
    fn test_disallowed_file_scheme() {
        // ensure_allowed_domain should reject file:// URLs.
        let result = ensure_allowed_domain("file:///etc/passwd");
        assert!(result.is_err());
    }

    #[test]
    fn test_manifest_allowlist_nonempty() {
        let m = manifest();
        assert!(!m.domain_allowlist.is_empty());
    }

    #[test]
    fn test_ensure_allowed_domain_valid() {
        let result = ensure_allowed_domain("https://maven.fabricmc.net/v2/versions/loader/1.21/0.19.0/profile/json");
        assert!(result.is_ok());
    }

    #[test]
    fn test_ensure_allowed_domain_invalid() {
        let result = ensure_allowed_domain("https://evil.example.com/loader.jar");
        assert!(result.is_err());
    }

    #[test]
    fn test_ensure_allowed_domain_invalid_url() {
        let result = ensure_allowed_domain("not-a-valid-url");
        assert!(result.is_err());
    }

    #[test]
    fn test_strip_sha_prefix() {
        assert_eq!(strip_sha_prefix("sha256:abc123"), "abc123");
        assert_eq!(strip_sha_prefix("abc123"), "abc123");
    }

    #[test]
    fn test_list_mc_versions_includes_legacy() {
        let versions = list_mc_versions(None);
        // Mojang's manifest includes versions back to 1.0.
        assert!(versions.len() > 50, "Expected 50+ versions, got {}", versions.len());
        assert!(versions.contains(&"1.12.2".to_string()), "1.12.2 should be in the list");
        assert!(versions.contains(&"1.7.10".to_string()), "1.7.10 should be in the list");
    }

    #[test]
    fn test_list_mc_versions_filtered_by_loader() {
        // When a loader is selected, only versions that loader supports appear.
        let all = list_mc_versions(None);
        let fabric = list_mc_versions(Some("fabric"));
        // Fabric should have fewer versions than the full list (it doesn't support 1.7.10 etc).
        assert!(fabric.len() < all.len(), "Fabric should have fewer versions than the full list");
        // Fabric shouldn't include 1.7.10 (too old for Fabric).
        assert!(!fabric.contains(&"1.7.10".to_string()), "Fabric should not support 1.7.10");
    }
}
