use crate::error::{LauncherError, LauncherResult};
use serde::Deserialize;
use std::sync::OnceLock;

/// Embedded copy of `loader-manifests/loader_manifests.json`.
///
/// Generated by `scripts/fetch_loader_manifests.py` / `scripts/refresh_loader_manifests.py`.
/// Pinning happens at compile time; the launcher never trusts an unpinned loader version.
const LOADER_MANIFESTS: &str = include_str!("../../../loader-manifests/loader_manifests.json");

#[derive(Debug, Deserialize, Clone)]
pub struct LoaderEntry {
    pub mc_version: String,
    pub loader_version: String,
    pub source_url: String,
    pub sha256: String,
    pub file_name: String,
    pub file_type: String,
}

#[derive(Debug, Deserialize)]
struct LoaderManifests {
    #[serde(default)]
    domain_allowlist: Vec<String>,
    #[serde(default)]
    loaders: std::collections::BTreeMap<String, Vec<LoaderEntry>>,
}

static MANIFEST: OnceLock<LoaderManifests> = OnceLock::new();

/// Parse the embedded loader manifests once and cache the result.
fn manifest() -> &'static LoaderManifests {
    MANIFEST.get_or_init(|| {
        serde_json::from_str(LOADER_MANIFESTS).unwrap_or_else(|_| LoaderManifests {
            domain_allowlist: Vec::new(),
            loaders: std::collections::BTreeMap::new(),
        })
    })
}

/// Find a pinned loader entry for a `(loader, mc_version, loader_version)` tuple.
pub fn find_entry(
    loader: &str,
    mc_version: &str,
    loader_version: &str,
) -> Option<&'static LoaderEntry> {
    manifest()
        .loaders
        .get(loader)
        .and_then(|entries| {
            entries.iter().find(|e| {
                e.mc_version == mc_version && e.loader_version == loader_version
            })
        })
}

/// Verify that a URL's host is on the hard-coded modloader domain allowlist.
pub fn ensure_allowed_domain(raw_url: &str) -> LauncherResult<()> {
    let host = reqwest::Url::parse(raw_url)
        .map_err(|e| LauncherError::Generic {
            code: "ERR_UNTRUSTED_SOURCE".to_string(),
            message: format!("Invalid loader URL: {e}"),
        })?
        .host_str()
        .ok_or(LauncherError::UntrustedSource)?
        .to_string();

    if is_allowed_host(&host) {
        Ok(())
    } else {
        Err(LauncherError::UntrustedSource)
    }
}

/// Whether a host is on the embedded loader domain allowlist.
pub fn is_allowed_host(host: &str) -> bool {
    manifest().domain_allowlist.iter().any(|d| d == host)
}

/// List pinned loader entries for a loader + Minecraft version.
pub fn list_versions(loader: &str, mc_version: &str) -> Vec<&'static LoaderEntry> {
    manifest()
        .loaders
        .get(loader)
        .map(|entries| {
            entries
                .iter()
                .filter(|e| e.mc_version == mc_version)
                .collect()
        })
        .unwrap_or_default()
}

/// Convert a `sha256:hex` string to raw lowercase hex.
pub fn strip_sha_prefix(s: &str) -> &str {
    s.strip_prefix("sha256:").unwrap_or(s)
}
